site_name: napari-dv
site_description: Deltavision/MRC file reader for napari
site_author: Talley Lambert

theme: readthedocs

repo_url: https://github.com/tlambert03/napari-dv

pages:
- Home: index.md
